name: Lint environmental variables

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_BASEDIR: "${{ github.workspace }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize Submodules
        continue-on-error: true
        run: git submodule update --init --recursive

      - name: Fix wrong checkouts
        run: |
          cd ./external/lsplant/lsplant/src/main/jni/external/dex_builder
          git fetch
          git checkout master
          git submodule update --init --recursive

      - name: Write key
        if: ${{ ( github.event_name != 'pull_request' && github.ref == 'refs/heads/master' ) || github.ref_type == 'tag' }}
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
            echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
            echo androidKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
            echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
            echo androidStoreFile='key.jks' >> gradle.properties
            echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks
          fi

      - name: Show all results
        run: |
          git fetch origin --tags
          export BUMP_VERSION=$(git describe --tags --abbrev=0)
          echo BUMP_VERSION: $BUMP_VERSION
          echo `git rev-list --count --all`

